// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamm_2LW4YdCiYRtkXjA5218Tw30Q4ktY',
    appId: '1:497659608814:web:c0fa00ea80f740e2397dff',
    messagingSenderId: '497659608814',
    projectId: 'flutterlogin-c5d10',
    authDomain: 'flutterlogin-c5d10.firebaseapp.com',
    storageBucket: 'flutterlogin-c5d10.appspot.com',
    measurementId: 'G-LL5BR80E7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJivzqXRN_UU6bqqUuq5LldcGHHmzUzI',
    appId: '1:497659608814:android:2055e9385d2580a8397dff',
    messagingSenderId: '497659608814',
    projectId: 'flutterlogin-c5d10',
    storageBucket: 'flutterlogin-c5d10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RK0N_TXvuV3nyn-CSnVHpgoCsiuSKb8',
    appId: '1:497659608814:ios:de68597c0e44cfb5397dff',
    messagingSenderId: '497659608814',
    projectId: 'flutterlogin-c5d10',
    storageBucket: 'flutterlogin-c5d10.appspot.com',
    iosClientId:
        '497659608814-q1hhjo44281hphvdltdasbv5o9e31ohj.apps.googleusercontent.com',
    iosBundleId: 'com.example.logpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RK0N_TXvuV3nyn-CSnVHpgoCsiuSKb8',
    appId: '1:497659608814:ios:a32bc695efbb8b39397dff',
    messagingSenderId: '497659608814',
    projectId: 'flutterlogin-c5d10',
    storageBucket: 'flutterlogin-c5d10.appspot.com',
    iosClientId:
        '497659608814-qd3ne1m2ci48beovcfdnq36tgu4hk3gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.logpage.RunnerTests',
  );
}
